apiVersion: apps/v1 # The deployment is inside apps/v1 API object
kind: Deployment # The type of the object is Deployment
metadata:
  name: event-bus-depl # The name of the deployment
spec:
  replicas: 1 # Number of pods to create
  selector:
    matchLabels:
      app: event-bus # The label of the pod
  template:
    metadata:
      labels:
        app: event-bus # The label of the pod
    spec:
      containers:
        - name: event-bus # The name of the container
          image: blogs/event-bus:latest # The latest image to use
          imagePullPolicy: Never # Never pull the image from docker hub registry
          ports:
            - containerPort: 5555 # The port to expose

---
# Create the Cluster IP service for the event bus
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus #what pods we allow access to this service
  type: ClusterIP #type of service (Optional)
  ports:
    - name: event-bus
      protocol: TCP
      port: 5555
      targetPort: 5555
